package edu.utcn.feritoth.core;
// Generated Mar 15, 2013 10:24:45 PM by Hibernate Tools 3.2.1.GA

import org.json.simple.JSONObject;

/**
 * Administrator generated by hbm2java
 */
public class Administrator implements java.io.Serializable {

    private Integer administratorId;
    private String name;
    private String emailAddress;
    private String passcode;

    public Administrator() {
    }

    public Administrator(String name, String emailAddress, String passcode) {
        this.name = name;
        this.emailAddress = emailAddress;
        this.passcode = passcode;
    }

    public Integer getAdministratorId() {
        return this.administratorId;
    }

    public void setAdministratorId(Integer administratorId) {
        this.administratorId = administratorId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmailAddress() {
        return this.emailAddress;
    }

    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    public String getPasscode() {
        return this.passcode;
    }

    public void setPasscode(String passcode) {
        this.passcode = passcode;
    }

    @Override
    public String toString() {
        return "The current administrator is registered with the following credentials:\n"
                + "AdministratorID=" + administratorId + ",\n"
                + "Name=" + name + ",\n"
                + "E-mail Address=" + emailAddress + ",\n"
                + "Passcode=" + passcode + '.';
    }

    public String createAdministratorJson() {
        JSONObject adminJson = new JSONObject();
        adminJson.put("adminID", administratorId);
        adminJson.put("name", name);
        adminJson.put("emailAddress", emailAddress);
        adminJson.put("passcode", passcode);
        return adminJson.toString();
    }
}
