package edu.utcn.feritoth.core;
// Generated Mar 13, 2013 12:55:36 AM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import org.json.simple.JSONObject;

/**
 * Author generated by hbm2java
 */
public class Author implements Serializable {

    private int authorId;
    private String name;
    private String yearsOfLife;
    private String shortDescription;
    private String reference;
    private String image;

    public Author() {
    }

    public Author(String name, String yearsOfLife, String shortDescription, String reference, String image) {
        this.name = name;
        this.yearsOfLife = yearsOfLife;
        this.shortDescription = shortDescription;
        this.reference = reference;
        this.image = image;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getYearsOfLife() {
        return this.yearsOfLife;
    }

    public void setYearsOfLife(String yearsOfLife) {
        this.yearsOfLife = yearsOfLife;
    }

    public String getShortDescription() {
        return this.shortDescription;
    }

    public void setShortDescription(String shortDescription) {
        this.shortDescription = shortDescription;
    }

    public String getReference() {
        return this.reference;
    }

    public void setReference(String reference) {
        this.reference = reference;
    }

    public String getImage() {
        return this.image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    @Override
    public String toString() {
        return "The author in question is registered with the following credentials:\n"
                + "AuthorId:" + authorId + ",\n"
                + "Name:" + name + ",\n"
                + "Years Of Life:" + yearsOfLife + ",\n"
                + "Short Description:" + shortDescription + ",\n"
                + "Reference:" + reference + ",\n"
                + "Portrait:" + image + ".\n";
    }

    public String createAuthorJson() {
        JSONObject authorJson = new JSONObject();
        authorJson.put("userID", authorId);
        authorJson.put("name", name);
        authorJson.put("yearsOfLife", yearsOfLife);
        authorJson.put("shortDescription", shortDescription);
        authorJson.put("reference", reference);
        authorJson.put("portrait", image);
        return authorJson.toString();
    }
}
